project:
  type: website
  resources:
    - cv.pdf  

website:
  title: "Jose Toledo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: courses.qmd
        text: Courses
      - href: research.qmd
        text: Research

  page-footer:
    right: "&copy; 2024, Jose Toledo Luna"





format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
execute:
  freeze: auto
  



