project:
  type: website

website:
  title: "Jose Toledo"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: courses.qmd
        text: Cources

  page-footer:
    right: "&copy; 2024, Jose Toledo Luna"





format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
execute:
  freeze: auto
  



